# SITE CONFIGURATION
title: Damos Designs # your site title
author: Damien Gilliams # You :P
description: > # Meta description of Homepage
  Damos Designs
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://damosdesigns.com"
# SEO PLUGIN
social:
  name: Damien Gilliams
  links:
    - https://twitter.com/captain_damo
    - https://www.linkedin.com/in/damosdesigns
    - https://github.com/dgilliams

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Shop', link: '/shop'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  The designs of Damien Gilliams: Software Engineer & Digital Artist

hero_img: posts/2906_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: damosdesigns@gmail.com # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  dgilliams # replace with your_github_username or comment to remove link from footer
instagram_username: damos_designs # replace with your_instagram_username or comment to remove link from footer

# disqus:
  # shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
